var hash=document.getElementById('main_2022');
if(hash){
hash.innerHTML=atob('PHN0eWxlPgojYnV0dG9uewpjb2xvcjojMDAwOwp3aWR0aDoyNTBweDsKaGVpZ2h0OjUwcHg7CmJveC1zaGFkb3c6cmdiYSgwLCAwLCAwLCAwLjIpIC0xcHggMHB4IDZweDsKZm9udC1zaXplOjE4cHg7Cm1hcmdpbjphdXRvOwpsaW5lLWhlaWdodDo1MHB4Owpib3JkZXItYm90dG9tLWxlZnQtcmFkaXVzOjVweDsKYm9yZGVyLWJvdHRvbS1yaWdodC1yYWRpdXM6NXB4Owp0ZXh0LWFsaWduOmNlbnRlcjsKYmFja2dyb3VuZC1jb2xvcjojQ0VDRUNFOwpvcGFjaXR5Oi4xOwp9CiNoYXNoewpkaXNwbGF5OmJsb2NrOwptYXJnaW46YXV0bzsKcGFkZGluZzphdXRvOwpwYWRkaW5nLWxlZnQ6NDFweDsKYm9yZGVyOm5vbmU7Cm91dGxpbmU6bm9uZTsKY29sb3I6I2ZmZjsKYm9yZGVyLXRvcC1sZWZ0LXJhZGl1czo1cHg7CmJvcmRlci10b3AtcmlnaHQtcmFkaXVzOjVweDsKd2lkdGg6MjUwcHg7CmhlaWdodDo1MHB4OwpiYWNrZ3JvdW5kLWNvbG9yOiNDRUNFQ0U7Cn0KI2hhc2g6Oi13ZWJraXQtaW5wdXQtcGxhY2Vob2xkZXJ7CnRleHQtYWxpZ246Y2VudGVyOwpjb2xvcjojZmZmZmZmOwp9CiNoYXNoOi1tcy1pbnB1dC1wbGFjZWhvbGRlciB7IC8qIElFIDEwKyAqLwp0ZXh0LWFsaWduOmNlbnRlcjsKY29sb3I6I2ZmZmZmZjsKfQojaGFzaDo6LW1vei1wbGFjZWhvbGRlciB7IC8qIEZpcmVmb3ggMTkrICovCnRleHQtYWxpZ246Y2VudGVyOwpjb2xvcjojZmZmZmZmOwp9CiNoYXNoOi1tb3otcGxhY2Vob2xkZXIgeyAvKiBGaXJlZm94IDQgLSAxOCAqLwp0ZXh0LWFsaWduOmNlbnRlcjsKY29sb3I6I2ZmZmZmZjsKfQoubWFpbnsKZGlzcGxheTpibG9jazsKbWFyZ2luOmF1dG87CnBhZGRpbmc6YXV0bzsKYm9yZGVyOjJweCBkYXNoZWQgIzNmMzlmNzsKd2lkdGg6MzAwcHg7Cn0KI2Vycm9yewpkaXNwbGF5Om5vbmU7CmNvbG9yOiNmZmY7Cm1hcmdpbjphdXRvOwp0ZXh0LWFsaWduOmNlbnRlcjsKYmFja2dyb3VuZC1jb2xvcjpyZ2JhKDI1NSwgMCwgMCwgLjUpOwpib3JkZXI6MXB4IHNvbGlkIHJnYigyNTUsIDAsIDApOwpib3JkZXItcmFkaXVzOjEwcHg7CndpZHRoOjIwMHB4OwpoZWlnaHQ6NDBweDsKbGluZS1oZWlnaHQ6NDBweDsKbWFyZ2luLWJvdHRvbTo1cHg7Cn0KI3NwaW5uZXJ7CmRpc3BsYXk6bm9uZTsKYmFja2dyb25kOm5vbmU7CmJvcmRlci1yYWRpdXM6NTAlOwp3aWR0aDozMHB4OwpoZWlnaHQ6MzBweDsKYm9yZGVyOjRweCBzb2xpZCAjYWFhOwpib3JkZXItcmlnaHQtY29sb3I6M2YzOWY3OwptYXJnaW4tdG9wOi00Mi41cHg7Cm1hcmdpbi1sZWZ0OjMwcHg7CmFuaW1hdGlvbjogcm90YXRlIC41cyBpbmZpbml0ZTsKfQpAa2V5ZnJhbWVzIHJvdGF0ZXsKICAgIDB7IHRyYW5zZm9ybTogcm90YXRlKDBkZWcpIH0KICAgIDEwMCUgeyB0cmFuc2Zvcm06IHJvdGF0ZSgzNjBkZWcpIH0KfQojZGVoYXNoewpkaXNwbGF5Om5vbmU7Cm1hcmdpbjphdXRvOwpwYWRkaW5nOmF1dG87CmZvbnQtc2l6ZToxOHB4OwptYXJnaW4tdG9wOjEwcHg7CnBhZGRpbmctcmlnaHQ6NXB4Owpib3JkZXItcmFkaXVzOjRweDsKd2lkdGg6MjYwcHg7CmhlaWdodDo0NXB4Owpib3JkZXI6MXB4IHNvbGlkICNlZWU7Cn0KPC9zdHlsZT4KPGRpdiBjbGFzcz0nbWFpbicgZGlyPSdydGwnIGxhbmc9J2FyJz4KPGJyLz4KPGRpdiBpZD0nZXJyb3InPjwvZGl2Pgo8aW5wdXQgZGlyPSdsdHInIGlkPSdoYXNoJyBwbGFjZWhvbGRlcj0nRW50ZXIgSGFzaCBtZDUnLz4KPGRpdiBkaXI9J2x0cic+Cjxzdmcgc3R5bGU9J3dpZHRoOjQwcHg7bWFyZ2luLXRvcDotNDVweDttYXJnaW4tbGVmdDoyNXB4JyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgNjQgNjQiPjxwYXRoIGQ9Im0yNi44NDIgMzZoOC4xMzdsMi4xNzktOGgtOC4xMzd6IiBmaWxsPSIjQzg5RDAyIi8+PHBhdGggZD0iTTMyLDJDMTUuNDMyLDIsMiwxNS40MzIsMiwzMnMxMy40MzIsMzAsMzAsMzBzMzAtMTMuNDMyLDMwLTMwUzQ4LjU2OCwyLDMyLDJ6IE00OS4zNjUsMjhoLTYuMTA0bC0yLjE4LDhoNi4xMDJsLTEuNjM1LDYKCQloLTYuMTA0bC0xLjYzNSw2aC02LjEwNGwxLjYzNy02aC04LjEzOWwtMS42MzUsNmgtNi4xMDRsMS42MzctNkgxM2wxLjYzNS02aDYuMTA0bDIuMTgtOGgtNi4xMDJsMS42MzUtNmg2LjEwMmwxLjYzNy02aDYuMTAyCgkJbC0xLjYzNSw2aDguMTM3bDEuNjM3LTZoNi4xMDJsLTEuNjM1LDZINTFMNDkuMzY1LDI4eiIgZmlsbD0iI0M4OUQwMiIvPjwvc3ZnPgo8L2Rpdj4KPGRpdiBpZD0iYnV0dG9uIj7Yo9ix2LPYp9mEPC9kaXY+CjxkaXYgZGlyPSdsdHInPjxkaXYgaWQ9J3NwaW5uZXInPjwvZGl2PjwvZGl2Pgo8ZGl2IGlkPSdkZWhhc2gnPjwvZGl2Pgo8YnIvPgo8L2Rpdj4=');
const hash=document.getElementById('hash');
function check(){
if(hash.value.length>0){
if((hash.value.length==32)&&(hash.value.indexOf(' ')<0)){
document.getElementById('error').style.display='none';
document.getElementById('button').style.background='none';
document.getElementById('button').style.opacity='1';
const p=document.querySelectorAll('#button');
for (var i = 0;i<p.length; i++) {
p[i].addEventListener('mouseover', function() {
document.getElementById('spinner').style.display='block';
document.getElementById('button').innerHTML='الرجاء الانتظار لحظة…';
var s='النتيجة:';
document.getElementById('dehash').innerHTML=s+'<iframe style="border:none;height:30px;width:200px;font-size:18px;margin-bottom:-10px;margin-top:5px;" src="http://www.nitrxgen.net/md5db/'+hash.value+'"></iframe>';
setTimeout(function(){
document.getElementById('spinner').style.display='none';
document.getElementById('button').innerHTML='أرسال';
document.getElementById('dehash').style.display='block';},
5000)
 });
}
}else{
document.getElementById('dehash').style.display='none';
document.getElementById('button').style.backgroundColor='#CECECE';
document.getElementById('button').style.opacity='0.1';
document.getElementById('error').style.display='block';
document.getElementById('error').innerHTML='يرجى ادخال hash md5';
}
}else{
document.getElementById('dehash').style.display='none';
document.getElementById('button').style.backgroundColor='#CECECE';
document.getElementById('button').style.opacity='0.1';
document.getElementById('error').style.display='none';
document.getElementById('error').innerHTML='';
}
setTimeout('check()',0);
}
check()
}